PYTORCH TENSORS 

In [12]:
import torch

torch.__version__

'1.10.0+cpu'

In [13]:
torch.get_default_dtype()

torch.float32

In [17]:
t1 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
t1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [20]:
torch.is_tensor(t1)

True

In [21]:
torch.numel(t1)

9

In [23]:
ut1 = torch.Tensor(3,3)
ut1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Uninitialized Tensor:

In [24]:
it1 = torch.rand(3,3)
it1

tensor([[0.5728, 0.9844, 0.9260],
        [0.3315, 0.2223, 0.6068],
        [0.2042, 0.6188, 0.5551]])